name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: corepack enable
      - run: pnpm -v || npm i -g pnpm@9.6.0
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm typecheck
      - run: pnpm build